import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ModuleGrade {
  module: {
    code: string;
    name: string;
    creditHours: number;
  };
  letterGrade: string;
  gradePoint: number;
}

interface ExportData {
  programmeName: string;
  semesterName: string;
  moduleGrades: ModuleGrade[];
  gpa: number;
  totalCreditHours: number;
  passedModules: number;
  qualityPoints: number;
}

export const exportToPDF = (data: ExportData) => {
  const doc = new jsPDF();
  
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  
  doc.setFillColor(13, 110, 253);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('GAP - GPA Calculator', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Academic Performance Report', pageWidth / 2, 30, { align: 'center' });
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Programme:', 15, 55);
  doc.setFont('helvetica', 'normal');
  doc.text(data.programmeName, 45, 55);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Semester:', 15, 62);
  doc.setFont('helvetica', 'normal');
  doc.text(data.semesterName, 45, 62);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Date:', 15, 69);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date().toLocaleDateString('en-GB'), 45, 69);
  
  const tableData = data.moduleGrades.map(mg => [
    mg.module.code,
    mg.module.name,
    mg.module.creditHours.toString(),
    mg.letterGrade,
    mg.gradePoint.toFixed(1),
    (mg.gradePoint * mg.module.creditHours).toFixed(1)
  ]);
  
  autoTable(doc, {
    startY: 80,
    head: [['Module Code', 'Module Name', 'Credits', 'Grade', 'Grade Point', 'Quality Points']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [13, 110, 253],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10
    },
    bodyStyles: {
      fontSize: 9
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245]
    },
    columnStyles: {
      0: { cellWidth: 30 },
      1: { cellWidth: 65 },
      2: { cellWidth: 20, halign: 'center' },
      3: { cellWidth: 20, halign: 'center' },
      4: { cellWidth: 25, halign: 'center' },
      5: { cellWidth: 30, halign: 'center' }
    },
    margin: { left: 15, right: 15 }
  });
  
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  
  doc.setFillColor(240, 240, 240);
  doc.roundedRect(15, finalY, pageWidth - 30, 50, 3, 3, 'F');
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(13, 110, 253);
  doc.text('Semester GPA:', 20, finalY + 12);
  
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text(data.gpa.toFixed(2), 70, finalY + 12);
  
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Credit Hours: ${data.totalCreditHours}`, 20, finalY + 25);
  doc.text(`Modules Passed: ${data.passedModules}`, 20, finalY + 32);
  doc.text(`Total Quality Points: ${data.qualityPoints.toFixed(1)}`, 20, finalY + 39);
  
  let performance = '';
  let performanceColor: [number, number, number] = [0, 0, 0];
  
  if (data.gpa >= 4.5) {
    performance = 'Excellent Performance';
    performanceColor = [40, 167, 69];
  } else if (data.gpa >= 4.0) {
    performance = 'Very Good Performance';
    performanceColor = [13, 110, 253];
  } else if (data.gpa >= 3.5) {
    performance = 'Good Performance';
    performanceColor = [255, 193, 7];
  } else if (data.gpa >= 3.0) {
    performance = 'Satisfactory Performance';
    performanceColor = [108, 117, 125];
  } else if (data.gpa >= 2.0) {
    performance = 'Pass - Room for Improvement';
    performanceColor = [255, 152, 0];
  } else {
    performance = 'Below Average';
    performanceColor = [220, 53, 69];
  }
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(performanceColor[0], performanceColor[1], performanceColor[2]);
  doc.text(performance, pageWidth / 2, finalY + 25, { align: 'center' });
  
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.setFont('helvetica', 'italic');
  doc.text(
    'Generated by GAP - Official GPA Calculator for IAA',
    pageWidth / 2,
    pageHeight - 15,
    { align: 'center' }
  );
  
  doc.setFontSize(7);
  doc.text(
    'Developed by DTC Group',
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );
  
  const fileName = `GPA_Report_${data.semesterName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};
